2023-10-27 23:44:06,047 INFO    MainThread:18128 [wandb_setup.py:_flush():76] Current SDK version is 0.15.12
2023-10-27 23:44:06,047 INFO    MainThread:18128 [wandb_setup.py:_flush():76] Configure stats pid to 18128
2023-10-27 23:44:06,047 INFO    MainThread:18128 [wandb_setup.py:_flush():76] Loading settings from C:\Users\Drishti\.config\wandb\settings
2023-10-27 23:44:06,047 INFO    MainThread:18128 [wandb_setup.py:_flush():76] Loading settings from C:\Users\Drishti\calhacks_llm\VibeMaps\wandb\settings
2023-10-27 23:44:06,047 INFO    MainThread:18128 [wandb_setup.py:_flush():76] Loading settings from environment variables: {}
2023-10-27 23:44:06,047 INFO    MainThread:18128 [wandb_setup.py:_flush():76] Applying setup settings: {'_disable_service': False}
2023-10-27 23:44:06,047 INFO    MainThread:18128 [wandb_setup.py:_flush():76] Inferring run settings from compute environment: {'program_relpath': 'together_llm.py', 'program_abspath': 'C:\\Users\\Drishti\\calhacks_llm\\VibeMaps\\together_llm.py', 'program': 'together_llm.py'}
2023-10-27 23:44:06,047 INFO    MainThread:18128 [wandb_init.py:_log_setup():528] Logging user logs to C:\Users\Drishti\calhacks_llm\VibeMaps\wandb\run-20231027_234406-3vqt1p5t\logs\debug.log
2023-10-27 23:44:06,047 INFO    MainThread:18128 [wandb_init.py:_log_setup():529] Logging internal logs to C:\Users\Drishti\calhacks_llm\VibeMaps\wandb\run-20231027_234406-3vqt1p5t\logs\debug-internal.log
2023-10-27 23:44:06,047 INFO    MainThread:18128 [wandb_init.py:init():568] calling init triggers
2023-10-27 23:44:06,047 INFO    MainThread:18128 [wandb_init.py:init():575] wandb.init called with sweep_config: {}
config: {}
2023-10-27 23:44:06,047 INFO    MainThread:18128 [wandb_init.py:init():618] starting backend
2023-10-27 23:44:06,047 INFO    MainThread:18128 [wandb_init.py:init():622] setting up manager
2023-10-27 23:44:06,059 INFO    MainThread:18128 [backend.py:_multiprocessing_setup():105] multiprocessing start_methods=spawn, using: spawn
2023-10-27 23:44:06,064 INFO    MainThread:18128 [wandb_init.py:init():628] backend started and connected
2023-10-27 23:44:06,066 INFO    MainThread:18128 [wandb_init.py:init():720] updated telemetry
2023-10-27 23:44:06,147 INFO    MainThread:18128 [wandb_init.py:init():753] communicating run to backend with 90.0 second timeout
2023-10-27 23:44:06,349 ERROR   MainThread:18128 [wandb_init.py:init():779] encountered error: It appears that you do not have permission to access the requested resource. Please reach out to the project owner to grant you access. If you have the correct permissions, verify that there are no issues with your networking setup.(Error 403: Forbidden)
2023-10-27 23:44:06,437 ERROR   MainThread:18128 [wandb_init.py:init():1188] It appears that you do not have permission to access the requested resource. Please reach out to the project owner to grant you access. If you have the correct permissions, verify that there are no issues with your networking setup.(Error 403: Forbidden)
Traceback (most recent call last):
  File "C:\Users\Drishti\AppData\Local\Programs\PythonCodingPack\lib\site-packages\wandb\sdk\wandb_init.py", line 1170, in init
    run = wi.init()
  File "C:\Users\Drishti\AppData\Local\Programs\PythonCodingPack\lib\site-packages\wandb\sdk\wandb_init.py", line 785, in init
    raise error
wandb.errors.CommError: It appears that you do not have permission to access the requested resource. Please reach out to the project owner to grant you access. If you have the correct permissions, verify that there are no issues with your networking setup.(Error 403: Forbidden)
2023-10-27 23:44:07,492 WARNING MsgRouterThr:18128 [router.py:message_loop():77] message_loop has been closed
